name: Ksu timetable image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      
    - name: Set JDK 
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: gradle clean build -x test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/libs

    - name: Run project
      run: java -jar ./build/libs/KsuTimetable-1.0.0.jar
  
